### PR TITLE
tps should be float 59

### PR DESCRIPTION
**Pull request by lzxm160**
work on #59

### CODE REVIEW

**Comment by zjshen14** [comment]
Will this break compatibility?

**Comment by lizhefeng** [comment]
@lzxm160 Please refer to the same change on iotex-core api. https://github.com/iotexproject/iotex-core/blob/master/api/api.go#L262

**Comment by lzxm160** [comment]
> @lzxm160 Please refer to the same change on iotex-core api. https://github.com/iotexproject/iotex-core/blob/master/api/api.go#L262

ok

**Comment by lzxm160** [comment]
> Will this break compatibility?

https://github.com/iotexproject/iotex-core/blob/master/api/api.go#L278
like this add TpsFloat?

**Comment by lizhefeng** [comment]
@puncsky Will this be a breaking change for explorer?

**Pull request closed without merging**
